# -*- coding: utf-8 -*-
"""unit_economics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uYEqyZijE2Sl8Ne4wxWArNcd0VdjAqb
"""

import pandas as pd
import math
import plotly.graph_objects as go
from dash import html, dcc, dash_table
from styles import BRAND_COLORS, TITLE_STYLE, HEADER_WRAPPER

def render_unit_tab(finalizer):
    d1 = finalizer.d1.copy()
    d2 = finalizer.d2.copy()

    # --- 1. Calculations ---
    mask = d1['stage'].astype(str).eq('Payment Done')
    successful_deals = d1[mask].copy()
    revenue = d1.loc[mask, 'initial_amount_paid'].sum()
    t = int(mask.sum())
    b = (successful_deals['contact_id'].astype(str).nunique()
         if 'contact_id' in successful_deals.columns
         else successful_deals['contact_name'].astype(str).nunique())
    ua = d1['id'].nunique()
    c1 = (b / ua * 100) if ua else 0
    aov = (revenue / t) if t else 0
    apc = (t / b) if b else 0

    cltv = aov * apc
    ltv = (c1 / 100) * cltv
    ac = d2['spend'].sum() if 'spend' in d2.columns else 0
    cm = revenue - ac

    # --- 2. Main Unit Economics Table Data ---
    df_ue = pd.DataFrame([{
        'UA': f"{ua:,}", 'C1': f"{c1:.2f}%", 'B': f"{b:,}",
        'AOV': f"{aov:,.0f}€", 'T': f"{t:,}", 'APC': f"{apc:.2f}",
        'CLTV': f"{cltv:,.0f}€", 'LTV': f"{ltv:,.1f}€",
        'AC': f"{ac:,.0f}€", 'CM': f"{cm:,.0f}€", 'Revenue': f"{revenue:,.0f}€"
    }])

    # --- 3. Tree Visualization Logic ---
    H, W_TOP, W_L2, W_L3 = 0.075, 0.20, 0.18, 0.18
    DX, EDGE_PAD = 0.13, 0.004
    DY_UP, DY_DN = 0.012, -0.012
    y_top, y_l2, y_l3 = 0.90, 0.70, 0.50
    x_users, x_freq, x_aov = 0.18, 0.50, 0.82

    # Y-calculation for P, N, C (doubled length)
    parent_b = y_l2 - H/2 - EDGE_PAD
    child_t_base = (y_l3 + DY_DN) + H/2 + EDGE_PAD
    dx_sq = DX * DX
    dy_base = child_t_base - parent_b
    dy_new = -math.sqrt(4 * (dx_sq + dy_base**2) - dx_sq)
    y_p = (parent_b + dy_new) - H/2 - EDGE_PAD

    fig = go.Figure()

    def add_box(x, y, w, h, text, fill):
        fig.add_shape(type='rect', xref='x', yref='y', x0=x-w/2, y0=y-h/2, x1=x+w/2, y1=y+h/2,
                      line=dict(color='#333', width=1), fillcolor=fill, opacity=0.95)
        fig.add_annotation(x=x, y=y, text=text, showarrow=False, font=dict(size=11, color='#111'))

    def connect_boxes(xp, yp, xc, yc):
        fig.add_annotation(x=xc, y=yc+H/2+EDGE_PAD, ax=xp, ay=yp-H/2-EDGE_PAD,
                           xref='x', yref='y', axref='x', ayref='y',
                           showarrow=True, arrowhead=2, arrowwidth=1, arrowcolor='#000')

    C_BOX = {'rev':'#a6c8ff','users':'#c3f3c0','freq':'#e5ccff','aov':'#ffeaa7'}
    add_box(0.50, y_top, W_TOP, H, 'Revenue', C_BOX['rev'])
    add_box(x_users, y_l2, W_L2, H, 'Users', C_BOX['users'])
    add_box(x_freq,  y_l2, W_L2, H, 'Purchase<br>Frequency', C_BOX['freq'])
    add_box(x_aov,   y_l2, W_L2, H, 'Average<br>Order Value', C_BOX['aov'])

    add_box(x_users - DX, y_l3 + DY_UP, W_L3, H, 'All Users', C_BOX['users'])
    add_box(x_users + DX, y_p, W_L3, H, 'Paying Users', C_BOX['users'])
    add_box(x_freq - DX, y_l3 + DY_UP, W_L3, H, 'Active Users', C_BOX['freq'])
    add_box(x_freq + DX, y_p, W_L3, H, 'Number of<br>Purchases', C_BOX['freq'])
    add_box(x_aov - DX, y_l3 + DY_UP, W_L3, H, 'Avg # product', C_BOX['aov'])
    add_box(x_aov + DX, y_p, W_L3, H, 'Avg price<br>/ product', C_BOX['aov'])

    edges = [(0.5, y_top, x_users, y_l2), (0.5, y_top, x_freq, y_l2), (0.5, y_top, x_aov, y_l2),
             (x_users, y_l2, x_users-DX, y_l3+DY_UP), (x_users, y_l2, x_users+DX, y_p),
             (x_freq, y_l2, x_freq-DX, y_l3+DY_UP), (x_freq, y_l2, x_freq+DX, y_p),
             (x_aov, y_l2, x_aov-DX, y_l3+DY_UP), (x_aov, y_l2, x_aov+DX, y_p)]
    for xp, yp, xc, yc in edges: connect_boxes(xp, yp, xc, yc)

    fig.update_layout(template='plotly_white', height=520, margin=dict(l=10,r=10,t=10,b=10))
    fig.update_xaxes(visible=False, range=[0,1])
    fig.update_yaxes(visible=False, range=[0,1], scaleanchor='x', scaleratio=1)

    # --- 4. Hypothesis Table Data ---
    hypothesis_data = [
        {"Metric": "C1 (Checkout)", "Hypothesis": "H1: One-click + Reminder", "Effect": "Friction reduction → C1 growth by 2-4%"},
        {"Metric": "AOV (Avg Order Value)", "Hypothesis": "H2: Limited-time Bundle", "Effect": "Basket expansion → AOV growth by 5-8%"}
    ]

    return html.Div([
        html.Div([html.H2("Unit Economics Analysis & Growth Strategy", style=TITLE_STYLE)], style=HEADER_WRAPPER),

        # --- SECTION 1: MAIN TABLE ---
        html.Div([
            dash_table.DataTable(
                data=df_ue.to_dict('records'),
                columns=[{"name": i, "id": i} for i in df_ue.columns],
                style_header={'backgroundColor': BRAND_COLORS['bark'], 'color': 'white', 'fontWeight': 'bold'},
                style_cell={'textAlign': 'center', 'padding': '12px', 'fontFamily': 'Arial'},
                style_data={'fontWeight': 'bold', 'color': BRAND_COLORS['forest']}
            )
        ], style={'margin': '20px'}),

        # --- SECTION 2: METRIC TREE ---
        html.Div([
            html.H3("Business Metrics Hierarchy", style={'textAlign': 'center', 'color': BRAND_COLORS['bark'], 'marginTop': '40px'}),
            dcc.Graph(figure=fig, config={'displayModeBar': False})
        ], style={'backgroundColor': 'white', 'padding': '20px', 'borderRadius': '10px', 'margin': '20px'}),

        # --- SECTION 3: STRATEGY BLOCK ---
        html.Div([
            html.H3("Growth Points (Unit Economics Insights)", style={'color': BRAND_COLORS['forest']}),
            html.Ul([
                html.Li("If CLV − CAC is low: raise AOV (bundles) or reduce CAC (better targeting)."),
                html.Li("If Contribution Margin is thin: cut discounts where elasticity is low; optimize ROI sources.")
            ]),

            html.Hr(style={'margin': '30px 0', 'border': f'1px solid {BRAND_COLORS["gold"]}'}),

            html.H3("Hypotheses:", style={'color': BRAND_COLORS['forest']}),
            html.P([html.B("H1: "), "One-click payment link + reminder @ T+24h to lift C1 by +2–4 p.p."]),
            html.P([html.B("H2: "), "Limited-time bundle (main + add-on -10%) to lift AOV by +5–8%."]),

            html.Div([
                dash_table.DataTable(
                    data=hypothesis_data,
                    columns=[{"name": i, "id": i} for i in ["Metric", "Hypothesis", "Effect"]],
                    style_header={'backgroundColor': BRAND_COLORS['bark'], 'color': 'white', 'fontWeight': 'bold'},
                    style_cell={'textAlign': 'left', 'padding': '12px', 'fontFamily': 'Arial', 'whiteSpace': 'normal', 'height': 'auto'}
                )
            ], style={'marginTop': '20px'}),

            html.Div([
                html.H4("Validation Method:", style={'marginTop': '30px', 'fontWeight': 'bold'}),
                html.P("Method: A/B testing on new user segments."),
                html.P([html.B("Success Condition: "), "Accepted if 95% confidence (p < 0.05) lift in target metric without cannibalization."])
            ], style={'backgroundColor': '#f9f9f9', 'padding': '20px', 'borderRadius': '10px', 'marginTop': '20px'})

        ], style={'padding': '40px', 'backgroundColor': 'white', 'margin': '20px', 'borderRadius': '10px'})
    ])